name: GitHub Pages deploy
on:
  push:
    branches:
    - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Dependancies
      run: |
        sudo apt install jupyter-core jupyter-nbconvert

    - name: Build
      run: |
        jupyter nbconvert --config nbconfig.py

    - name: Deploy to GitHub Pages
      uses: Cecilapp/GitHub-Pages-deploy@v3
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        email: ryan.littleton0@gmail.com
        build_dir: 'docs'
        branch: 'docs-branch'